### ISSUE TITLE
OutOfMemoryError on arm

### ISSUE THREAD

**Issue by WisniewskiP** [jfrog/bamboo-artifactory-plugin#129]
**Describe the bug**
Starting bamboo agent on Raspberry Pi it takes a long time (~10min) and reports out of memory

**To Reproduce**
Run bamboo agent in Docker on Raspberry Pi 3 with Artifactory plugin installed

**Expected behavior**
Starts in a few seconds and without exception.

**Screenshots**
```
2020-11-17 09:50:01,091 INFO [AgentRunnerThread] [ClasspathBuilder] Collection user-installed-plugins downloaded
2020-11-17 09:58:48,469 ERROR [AgentRunnerThread] [ScanningPluginLoader] Unable to deploy plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' from 'Unit: /bamboo/plugins/user-installed/plugin.5918164098591352241.bamboo-artifactory-plugin-3.1.0.jar (1605606601000)'.
2020-11-17 09:58:48,484 ERROR [AgentRunnerThread] [ScanningPluginLoader] Because of the following exception:
java.lang.OutOfMemoryError: Java heap space
        at aQute.bnd.osgi.Clazz.ref(Clazz.java:859)
        at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:574)
        at aQute.bnd.osgi.Clazz.parseClassFileData(Clazz.java:509)
        at aQute.bnd.osgi.Clazz.parseClassFileWithCollector(Clazz.java:494)
        at aQute.bnd.component.AnnotationReader.getDef(AnnotationReader.java:134)
        at aQute.bnd.component.AnnotationReader.getDefinition(AnnotationReader.java:130)
        at aQute.bnd.component.DSAnnotations.analyzeJar(DSAnnotations.java:126)
        at aQute.bnd.osgi.Analyzer.doPlugins(Analyzer.java:664)
        at aQute.bnd.osgi.Analyzer.analyze(Analyzer.java:216)
        at aQute.bnd.osgi.Builder.analyze(Builder.java:387)
        at aQute.bnd.osgi.Analyzer.calcManifest(Analyzer.java:694)
        at com.atlassian.plugin.osgi.factory.transform.stage.GenerateManifestStage.execute(GenerateManifestStage.java:191)
        at com.atlassian.plugin.osgi.factory.transform.DefaultPluginTransformer.transform(DefaultPluginTransformer.java:140)
        at com.atlassian.plugin.osgi.factory.OsgiPluginFactory.createOsgiPluginJar(OsgiPluginFactory.java:307)
        at com.atlassian.plugin.osgi.factory.OsgiPluginFactory.create(OsgiPluginFactory.java:224)
        at com.atlassian.plugin.loaders.ScanningPluginLoader.deployPluginFromUnit(ScanningPluginLoader.java:145)
        at com.atlassian.plugin.loaders.ScanningPluginLoader.loadAllPlugins(ScanningPluginLoader.java:90)
        at com.atlassian.plugin.loaders.PermissionCheckingPluginLoader.loadAllPlugins(PermissionCheckingPluginLoader.java:28)
        at com.atlassian.plugin.manager.DefaultPluginManager.lambda$earlyStartup$3(DefaultPluginManager.java:539)
        at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$107/13505658.run(Unknown Source)
        at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
        at com.atlassian.plugin.manager.DefaultPluginManager.earlyStartup(DefaultPluginManager.java:523)
        at com.atlassian.plugin.manager.DefaultPluginManager.lambda$init$2(DefaultPluginManager.java:515)
        at com.atlassian.plugin.manager.DefaultPluginManager$$Lambda$106/10580068.run(Unknown Source)
        at com.atlassian.plugin.manager.PluginTransactionContext.wrap(PluginTransactionContext.java:63)
        at com.atlassian.plugin.manager.DefaultPluginManager.init(DefaultPluginManager.java:514)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeCustomInitMethod(AbstractAutowireCapableBeanFactory.java:1904)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1846)
```

**Versions**
- Bamboo Artifactory plugin version: 3.1.0 
- Bamboo operating system: Ubuntu 18.04
- Artifactory Version: 6.16.2
- Bamboo Agent os: Ubuntu 18.04 inside docker on Raspberry Pi 3

**Additional context**
I didn't tested it without docker.

**Comment by yahavi** [comment]
Thanks for reporting this issue, @WisniewskiP!
It is a known issue. Fortunately, users already reported that increasing the heap size of the Bamboo agent resolved this issue for them. 
The default agent's heap size of Bamboo remote agents is very small - 512 MB, not enough for running Bamboo plans with external Bamboo apps.

Would you like to increase the Java heap size to 1024 MB?
In the agent's machine, simply change `BAMBOO_AGENT_HOME/conf/wrapper.conf`:
```properties
# Initial Java Heap Size (in MB)
wrapper.java.initmemory=512
# Maximum Java Heap Size (in MB)
wrapper.java.maxmemory=1024
```
For more information see: [OutOfMemory Errors in Bamboo server or in remote agent](https://confluence.atlassian.com/bamkb/outofmemory-errors-in-bamboo-server-or-in-remote-agent-307038120.html).

Please let me know if it helped.

**Comment by WisniewskiP** [comment]
Thanks for suggestion, Heap was the problem.

now I have different Problem Raspberry PI has only 1GB Ram.
but I found value below that and it works.
