### ISSUE TITLE
Plugin installs but will not enable after upgrading to Bamboo 7.2.5

### ISSUE THREAD

**Issue by mdtrostle** [jfrog/bamboo-artifactory-plugin#150]
**Describe the bug**
Plugin can't be enabled after upgrading Bamboo to 7.2.5 and upgrading the plugin to 3.2.3

**To Reproduce**
Un-installed and re-installed the plugin and it fails to start

**Expected behavior**
The plugin to work and enabled with the compatible Bamboo version

**Screenshots**
![Screen Shot 2021-09-08 at 11 59 38 AM](https://user-images.githubusercontent.com/90339103/132543975-14d8d35b-ec56-499c-a2db-f4a80baa5001.png)

**Versions**
- Bamboo Artifactory plugin version: 3.2.3
- Bamboo operating system: RHEL 7.9
- Artifactory Version: currently 5.13 (but not the problem and upgrading to 6.X this week-end)

**Additional context**
Error log: 

 2021-09-08 11:41:21,609 ERROR [ThreadPoolAsyncTaskExecutor::Thread 44] [ExtenderConfiguration] Application context refresh failed (NonValidatingOsgiBundleXmlApplicationContext(bundle=org.jfrog.bamboo.bamboo-artifactory-plugin, config=osgibundle:/META-INF/spring/*.xml))
org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from URL [bundle://120.0:0/META-INF/spring/atlassian-plugins-component-imports.xml]; nested exception is java.lang.IllegalStateException: The bundle is uninstalled.
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:420)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:337)
        at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:305)
        at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:188)

**Comment by mdtrostle** [comment]
The issue was actually a misconfigured systemctl start/stop script.  This case is being closed.
