### ISSUE TITLE
Artifactory Plugin 3.2.10 crashes remote agent of Bamboo 9.x

### ISSUE THREAD

**Issue by aselmi** [jfrog/bamboo-artifactory-plugin#191]
**Describe the bug**
Remote agents of bamboo 9.x fail to start when the Artifactoy plugin is installed. Following Exception in the remote agent logs is thrown, which seems to be due to Logger creation:
`Exiting due to fatal exception.
 java.lang.reflect.InvocationTargetException
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.atlassian.bamboo.agent.bootstrap.AgentRunner.run(AgentRunner.java:27)
       at java.base/java.lang.Thread.run(Thread.java:834)
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'agentRegistrationBean': Invocation of init method failed; nested exception is io.atlassian.util.concurrent.LazyReference$InitializationException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.jfrog.bamboo.capability.Maven3CapabilityHelper': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:160)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.applyBeanPostProcessorsBeforeInitialization(AbstractAutowireCapableBeanFactory.java:440)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1796)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
       at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335)
       at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234)
       at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333)
       at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208)
       at org.springframework.beans.factory.support.DefaultListableBeanFactory.preInstantiateSingletons(DefaultListableBeanFactory.java:955)
       at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:918)
       at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:583)
       at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
       at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
       at com.atlassian.bamboo.v2.build.agent.remote.RemoteAgent$1.<init>(RemoteAgent.java:269)
       at com.atlassian.bamboo.v2.build.agent.remote.RemoteAgent.initApplicationContext(RemoteAgent.java:269)
       at com.atlassian.bamboo.v2.build.agent.remote.RemoteAgent.start(RemoteAgent.java:100)
       ... 6 more
 Caused by: io.atlassian.util.concurrent.LazyReference$InitializationException: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.jfrog.bamboo.capability.Maven3CapabilityHelper': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
       at io.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:156)
       at io.atlassian.util.concurrent.LazyReference.get(LazyReference.java:116)
       at io.atlassian.util.concurrent.ResettableLazyReference.get(ResettableLazyReference.java:95)
       at com.atlassian.bamboo.plugin.descriptor.TaskModuleDescriptorImpl.getCapabilityDefaultsHelper(TaskModuleDescriptorImpl.java:172)
       at com.atlassian.bamboo.v2.build.agent.capability.CapabilityDefaultsHelperImpl.getCapabilityDefaultsHelpers(CapabilityDefaultsHelperImpl.java:69)
       at com.atlassian.bamboo.v2.build.agent.capability.CapabilityDefaultsHelperImpl.addDefaultCapabilities(CapabilityDefaultsHelperImpl.java:32)
       at com.atlassian.bamboo.v2.build.agent.remote.AgentRegistrationBean.registerAgent(AgentRegistrationBean.java:46)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
       at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleElement.invoke(InitDestroyAnnotationBeanPostProcessor.java:389)
       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor$LifecycleMetadata.invokeInitMethods(InitDestroyAnnotationBeanPostProcessor.java:333)
       at org.springframework.beans.factory.annotation.InitDestroyAnnotationBeanPostProcessor.postProcessBeforeInitialization(InitDestroyAnnotationBeanPostProcessor.java:157)
       ... 22 more
 Caused by: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.jfrog.bamboo.capability.Maven3CapabilityHelper': Instantiation of bean failed; nested exception is java.lang.ExceptionInInitializerError
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1334)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBeanInstance(AbstractAutowireCapableBeanFactory.java:1232)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:582)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:378)
       at jdk.internal.reflect.GeneratedMethodAccessor28.invoke(Unknown Source)
       at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
       at java.base/java.lang.reflect.Method.invoke(Method.java:566)
       at com.atlassian.plugin.osgi.spring.DefaultSpringContainerAccessor.createBean(DefaultSpringContainerAccessor.java:116)
       at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.instantiateClass(AbstractBambooModuleDescriptor.java:110)
       at com.atlassian.bamboo.plugin.descriptor.TaskModuleDescriptorImpl$2.create(TaskModuleDescriptorImpl.java:81)
       at com.atlassian.bamboo.plugin.descriptor.TaskModuleDescriptorImpl$2.create(TaskModuleDescriptorImpl.java:74)
       at io.atlassian.util.concurrent.ResettableLazyReference$InternalReference.create(ResettableLazyReference.java:185)
       at io.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:332)
       at io.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:150)
       ... 35 more
 Caused by: java.lang.ExceptionInInitializerError
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
       at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
       at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
       at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
       at org.springframework.beans.BeanUtils.instantiateClass(BeanUtils.java:211)
       at org.springframework.beans.factory.support.SimpleInstantiationStrategy.instantiate(SimpleInstantiationStrategy.java:87)
       at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.instantiateBean(AbstractAutowireCapableBeanFactory.java:1326)
       ... 49 more
 Caused by: java.lang.StringIndexOutOfBoundsException: begin 0, end -1, length 9
       at java.base/java.lang.String.checkBoundsBeginEnd(String.java:3319)
       at java.base/java.lang.String.substring(String.java:1874)
       at org.apache.logging.log4j.util.PropertiesUtil.partitionOnCommonPrefixes(PropertiesUtil.java:555)
       at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationBuilder.build(PropertiesConfigurationBuilder.java:174)
       at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:56)
       at org.apache.logging.log4j.core.config.properties.PropertiesConfigurationFactory.getConfiguration(PropertiesConfigurationFactory.java:35)
       at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:557)
       at org.apache.logging.log4j.core.config.ConfigurationFactory$Factory.getConfiguration(ConfigurationFactory.java:481)
       at org.apache.logging.log4j.core.config.ConfigurationFactory.getConfiguration(ConfigurationFactory.java:323)
       at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:695)
       at org.apache.logging.log4j.core.LoggerContext.reconfigure(LoggerContext.java:716)
       at org.apache.logging.log4j.core.LoggerContext.start(LoggerContext.java:270)
       at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:155)
       at org.apache.logging.log4j.core.impl.Log4jContextFactory.getContext(Log4jContextFactory.java:47)
       at org.apache.logging.log4j.LogManager.getContext(LogManager.java:196)
       at org.apache.logging.log4j.LogManager.getLogger(LogManager.java:599)
       at org.jfrog.bamboo.capability.Maven3CapabilityHelper.<clinit>(Maven3CapabilityHelper.java:30)
       ... 56 more
 2022-11-03 15:39:00,165 FATAL [AgentRunnerThread] [RemoteAgentBootstrap] Exiting due to fatal exception.`

**To Reproduce**
Install Artifactory Bamboo plugin 3.2.10 on Bamboo 9.x and restart the remote agent

**Expected behavior**
Remote agent should start smoothly even when Artifactoy plugin is installed

**Versions**
- Bamboo Artifactory plugin version: 3.2.10
- Bamboo operating system: Oracle Linux Server 8.3
- Artifactory Version: 7.35.2

**Comment by RobiNino** [comment]
Hi @aselmi 
Bamboo Artifactory plugin version 3.3.0 was just released and is compatible with Bamboo 9.2.1.
We'd appreciate your feedback for it.
Thank you for your patience.
