### ISSUE TITLE
nuget push getting 404 after upgrade

### ISSUE THREAD

**Issue by tobmat** [jfrog/bamboo-artifactory-plugin#200]
**Describe the bug**
After upgrading from 3.29. to 3.3.1 I am getting the following error from bamboo build task: Nuget push build artifacts

```
16-May-2023 15:14:50 | [consumer_0] Deploying artifact: https://artifactory.xxx.com/artifactory/duckcreek-nuget-local/develop/1.7.0-rc8/MedPro.Build.1.7.0-rc8.nupkg
16-May-2023 15:14:50 | Failed to upload file
16-May-2023 15:14:50 | [consumer_0] An exception occurred during execution:java.lang.RuntimeException: java.io.IOException: JFrog service failed. Received 404: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
31-Dec-1969 19:00:00 | <html xmlns="http://www.w3.org/1999/xhtml">
31-Dec-1969 19:00:00 | <head>
31-Dec-1969 19:00:00 | <meta http-equiv="Content-Type" content="text/html; charset=iso-8859-1"/>
31-Dec-1969 19:00:00 | <title>404 - File or directory not found.</title>
31-Dec-1969 19:00:00 | <style type="text/css">
31-Dec-1969 19:00:00 | <!--
31-Dec-1969 19:00:00 | body{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}
31-Dec-1969 19:00:00 | fieldset{padding:0 15px 10px 15px;}
31-Dec-1969 19:00:00 | h1{font-size:2.4em;margin:0;color:#FFF;}
31-Dec-1969 19:00:00 | h2{font-size:1.7em;margin:0;color:#CC0000;}
31-Dec-1969 19:00:00 | h3{font-size:1.2em;margin:10px 0 0 0;color:#000000;}
31-Dec-1969 19:00:00 | #header{width:96%;margin:0 0 0 0;padding:6px 2% 6px 2%;font-family:"trebuchet MS", Verdana, sans-serif;color:#FFF;
31-Dec-1969 19:00:00 | background-color:#555555;}
31-Dec-1969 19:00:00 | #content{margin:0 0 0 2%;position:relative;}
31-Dec-1969 19:00:00 | .content-container{background:#FFF;width:96%;margin-top:8px;padding:10px;position:relative;}
31-Dec-1969 19:00:00 | -->
31-Dec-1969 19:00:00 | </style>
31-Dec-1969 19:00:00 | </head>
31-Dec-1969 19:00:00 | <body>
31-Dec-1969 19:00:00 | <div id="header"><h1>Server Error</h1></div>
31-Dec-1969 19:00:00 | <div id="content">
31-Dec-1969 19:00:00 | <div class="content-container"><fieldset>
31-Dec-1969 19:00:00 | <h2>404 - File or directory not found.</h2>
31-Dec-1969 19:00:00 | <h3>The resource you are looking for might have been removed, had its name changed, or is temporarily unavailable.</h3>
31-Dec-1969 19:00:00 | </fieldset></div>
31-Dec-1969 19:00:00 | </div>
31-Dec-1969 19:00:00 | </body>
31-Dec-1969 19:00:00 | </html>
31-Dec-1969 19:00:00 |  
31-Dec-1969 19:00:00 | at org.jfrog.build.extractor.clientConfiguration.util.spec.SpecDeploymentConsumer.consumerRun(SpecDeploymentConsumer.java:44)
31-Dec-1969 19:00:00 | at org.jfrog.build.extractor.producerConsumer.ConsumerRunnableBase.run(ConsumerRunnableBase.java:11)
31-Dec-1969 19:00:00 | at java.base/java.lang.Thread.run(Thread.java:829)
31-Dec-1969 19:00:00 | Caused by: java.io.IOException: JFrog service failed. Received 404: <!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
```

**To Reproduce**
Run Artifactory Nuget configuration set to push and run.

**Expected behavior**
Expect artifacts to be pushed.

**Screenshots**
![Screenshot-bamboo-task-config](https://github.com/jfrog/bamboo-artifactory-plugin/assets/8656463/3c7fa802-c119-4a36-8c42-82db527eb83b)

**Versions**
- Bamboo Artifactory plugin version: 3.3.1 (upgraded from 3.2.9 which was working)
- Bamboo operating system: 8.2.8 (Data Center)
- Artifactory Version: 7.35.2 (on-prem windows deployment)

**Additional context**

**Comment by tobmat** [comment]
Additional Info:

- Generic Deploy still worked on versions 3.2.10 and 3.3.0.  Broke with 3.3.1
- Artifactory Nuget configuration (Push) - worked on 3.2.10 but got error listed above on 3.3.0

**Comment by tobmat** [comment]
I have discovered the issue.  The Artifactory nuget push fails with a 404 if spaces are in the Build Name.  I changed to use the buildKey variable (no spaces) and it worked.  FYI this is also an issue with the jfrog cli when attempting to upload nuget artifacts with build info.

<img width="260" alt="image" src="https://github.com/jfrog/bamboo-artifactory-plugin/assets/8656463/6c4df982-c9b8-46ba-b4ca-ba93e21b0332">
