### ISSUE TITLE
Support for Bamboo 5.10.x

### ISSUE THREAD

**Issue by aconstantin** [jfrog/bamboo-artifactory-plugin#22]
The current version `1.9.2` of your plugin, is incompatible with the latest `5.10.0` release of the Bamboo Server. 
It would be great if there would be a new release of your plugin compatible with `5.10.0`

```
Caused by: java.lang.NoSuchMethodError: com.atlassian.bamboo.security.SecureTokenService.generate(Lcom/atlassian/bamboo/ResultKey;)Lcom/atlassian/bamboo/security/SecureToken;
    at org.jfrog.bamboo.release.provider.TokenDataProvider.populateRuntimeTaskData(TokenDataProvider.java:30)
    at com.atlassian.bamboo.chains.ChainPluginSupportHelper.prepareRuntimeTaskData(ChainPluginSupportHelper.java:39)
```

Thanks for your help

**Comment by eyalbe4** [comment]
Thanks for reporting this. We are on it.

**Comment by eyalbe4** [comment]
We'll soon publish a snapshot on top of version 1.9.2 of the plugin with a compatibility fix.
Please follow [BAP-336](https://www.jfrog.com/jira/browse/BAP-336) for updates.
