### ISSUE TITLE
Installing the plugin in bamboo docker breaks the docker image

### ISSUE THREAD

**Issue by earthquakesan** [jfrog/bamboo-artifactory-plugin#59]
Minimal docker image:
```
FROM atlassian/bamboo-server:6.6.2

USER root
ENV ARTIFACTORY_PLUGIN_VERSION 2.4.1
RUN echo "configurate bamboo and jfrog integration" \
   && apt-get install -y wget \
   && wget https://dl.bintray.com/jfrog/jfrog-jars/org/jfrog/bamboo/bamboo-artifactory-plugin/${ARTIFACTORY_PLUGIN_VERSION}/bamboo-artifactory-plugin-${ARTIFACTORY_PLUGIN_VERSION}.jar -O "${BAMBOO_SERVER_INSTALL_DIR}/atlassian-bamboo/WEB-INF/lib/bamboo-artifactory-plugin-${ARTIFACTORY_PLUGIN_VERSION}.jar"
USER ${BAMBOO_USER}
```

Steps to reproduce:
```
docker build -t bamboo-with-artifactory-plugin .
docker run -it --rm -v /data/home/bamboo:/var/atlassian/application-data/bamboo -p 8085:8085 -p 54663:54663 bamboo-with-artifactory-plugin
```

Error output:
```
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,181 INFO [localhost-startStop-1] [lifecycle] *******************************
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,181 INFO [localhost-startStop-1] [lifecycle] *   Bamboo is starting up     *
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,182 INFO [localhost-startStop-1] [lifecycle] *******************************
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,183 INFO [localhost-startStop-1] [ServletContextHolder] Setting servlet context: Bamboo
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,239 INFO [localhost-startStop-1] [lifecycle] atlassian.org.osgi.framework.bootdelegation set to javax.servlet,javax.servlet.*,sun.*,com.sun.*,org.w3c.dom.*,org.apache.xerces.*,org.jboss.byteman.*,jdk.internal.reflect
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,384 INFO [localhost-startStop-1] [BootstrapLoaderListener] App classloader is the same as web app classloader
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,843 FATAL [localhost-startStop-1] [BootstrapLoaderListener] An error was encountered while bootstrapping Bamboo (see below):
bamboo.eccenca.com_bamboo | Unexpected exception parsing XML document from class path resource [applicationContextBootstrap.xml]; nested exception is java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
bamboo.eccenca.com_bamboo | org.springframework.beans.factory.BeanDefinitionStoreException: Unexpected exception parsing XML document from class path resource [applicationContextBootstrap.xml]; nested exception is java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:413)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:335)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.loadBeanDefinitions(XmlBeanDefinitionReader.java:303)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:187)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:223)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:194)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.support.AbstractBeanDefinitionReader.loadBeanDefinitions(AbstractBeanDefinitionReader.java:258)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:128)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.AbstractXmlApplicationContext.loadBeanDefinitions(AbstractXmlApplicationContext.java:94)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.AbstractRefreshableApplicationContext.refreshBeanFactory(AbstractRefreshableApplicationContext.java:133)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.AbstractApplicationContext.obtainFreshBeanFactory(AbstractApplicationContext.java:621)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:522)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:144)
bamboo.eccenca.com_bamboo | 	at org.springframework.context.support.ClassPathXmlApplicationContext.<init>(ClassPathXmlApplicationContext.java:95)
bamboo.eccenca.com_bamboo | 	at com.atlassian.bamboo.setup.BootstrapLoaderListener.contextInitialized(BootstrapLoaderListener.java:89)
bamboo.eccenca.com_bamboo | 	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4842)
bamboo.eccenca.com_bamboo | 	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5303)
bamboo.eccenca.com_bamboo | 	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:147)
bamboo.eccenca.com_bamboo | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1407)
bamboo.eccenca.com_bamboo | 	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1397)
bamboo.eccenca.com_bamboo | 	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
bamboo.eccenca.com_bamboo | 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
bamboo.eccenca.com_bamboo | 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
bamboo.eccenca.com_bamboo | 	at java.lang.Thread.run(Thread.java:748)
bamboo.eccenca.com_bamboo | Caused by: java.lang.NoSuchMethodError: org.slf4j.spi.LocationAwareLogger.log(Lorg/slf4j/Marker;Ljava/lang/String;ILjava/lang/String;[Ljava/lang/Object;Ljava/lang/Throwable;)V
bamboo.eccenca.com_bamboo | 	at org.apache.commons.logging.impl.SLF4JLocationAwareLog.debug(SLF4JLocationAwareLog.java:133)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.DefaultBeanDefinitionDocumentReader.registerBeanDefinitions(DefaultBeanDefinitionDocumentReader.java:96)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.registerBeanDefinitions(XmlBeanDefinitionReader.java:507)
bamboo.eccenca.com_bamboo | 	at org.springframework.beans.factory.xml.XmlBeanDefinitionReader.doLoadBeanDefinitions(XmlBeanDefinitionReader.java:391)
bamboo.eccenca.com_bamboo | 	... 23 more
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,848 WARN [localhost-startStop-1] [BootstrapUtils] Attempting to retrieve bootstrap manager before it is set up: com.atlassian.config.bootstrap.BootstrappedContextLoaderListener.canInitialiseContainer(BootstrappedContextLoaderListener.java:24)
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,857 WARN [localhost-startStop-1] [BootstrapUtils] Attempting to retrieve bootstrap manager before it is set up: com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:56)
bamboo.eccenca.com_bamboo | 26-Sep-2018 14:52:42.860 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
bamboo.eccenca.com_bamboo | 26-Sep-2018 14:52:42.873 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [] startup failed due to previous errors
bamboo.eccenca.com_bamboo | 2018-09-26 14:52:42,954 INFO [localhost-startStop-1] [BambooPluginManager] Plugin state will no longer be persisted.
bamboo.eccenca.com_bamboo | 26-Sep-2018 14:52:43.040 WARNING [localhost-startStop-1] org.apache.catalina.loader.WebappClassLoaderBase.clearReferencesJdbc The web application [ROOT] registered the JDBC driver [org.h2.Driver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
bamboo.eccenca.com_bamboo | 26-Sep-2018 14:52:43.061 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-nio-8085"]
```

Without the plugin bamboo server starts as intended. I have found this issue https://stackoverflow.com/questions/20537459/java-lang-nosuchmethoderror-org-slf4j-spi-locationawarelogger-log, which might be related.

P.S. If it is not the right place to discuss it, let me know please.

**Comment by shuvadipc** [comment]
Please use our newer bamboo-jfrog-plugin which will get all the new features, enhancements and support going forward.
