### ISSUE TITLE
Artifactory Plugin causes Bamboo 5.6.0 to not start

### ISSUE THREAD

**Issue by GrantGochnauer** [jfrog/bamboo-artifactory-plugin#6]
It looks like the version of Guava changed in Bamboo 5.6.0 and so on startup with this plugin installed, there is a NoClassDefFound exception.

```
org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.atlassian.bamboo.build.logger.DefaultBuildLoggerManager]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
Caused by: org.springframework.beans.BeanInstantiationException: Could not instantiate bean class [com.atlassian.bamboo.build.logger.DefaultBuildLoggerManager]: Constructor threw exception; nested exception is java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
Caused by: java.lang.NoSuchMethodError: com.google.common.cache.CacheBuilder.build(Lcom/google/common/cache/CacheLoader;)Lcom/google/common/cache/LoadingCache;
    at com.atlassian.bamboo.build.logger.DefaultBuildLoggerManager.<init>(DefaultBuildLoggerManager.java:37)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
    at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:57)
```

**Comment by sopel** [comment]
@elig - The mirror issue [BAP-218](https://www.jfrog.com/jira/browse/BAP-218) is resolved, so this one can be closed too I guess?!
