### ISSUE TITLE
Fails to load with Bamboo 5.8.1 OSS

### ISSUE THREAD

**Issue by gdude2002** [jfrog/bamboo-artifactory-plugin#9]
I started out with this error:

```
2015-05-28 14:51:51,740 WARN [localhost-startStop-1] [TaskModuleDescriptorImpl] Category definition for Task Type artifactoryGenericResolveTask of plugin org.jfrog.bamboo.bamboo-artifactory-plugin is not valid.  No such category as: resolve
2015-05-28 14:51:56,185 ERROR [localhost-startStop-1] [ScanningPluginLoader] Unable to deploy plugin 'com.atlassian.bamboo.plugins.atlassian-bamboo-plugin-git' from 'Unit: /opt/atlassian/bamboo/home/bundled-plugins/atlassian-bamboo-plugin-git-5.8.1.jar (1426576984000)'.
2015-05-28 14:51:56,185 ERROR [localhost-startStop-1] [ScanningPluginLoader] Because of the following exception:
java.lang.NoClassDefFoundError: com/jcraft/jsch/UserInfo
    at java.lang.Class.getDeclaredMethods0(Native Method)
    at java.lang.Class.privateGetDeclaredMethods(Class.java:2693)
    at java.lang.Class.privateGetPublicMethods(Class.java:2894)
    at java.lang.Class.getMethods(Class.java:1607)
    at com.atlassian.plugin.osgi.factory.transform.stage.HostComponentSpringStage.addHostComponentsUsedInSuperClasses(HostComponentSpringStage.java:256)
    at com.atlassian.plugin.osgi.factory.transform.stage.HostComponentSpringStage.findUsedHostComponents(HostComponentSpringStage.java:217)
    at com.atlassian.plugin.osgi.factory.transform.stage.HostComponentSpringStage.execute(HostComponentSpringStage.java:58)
    at com.atlassian.plugin.osgi.factory.transform.DefaultPluginTransformer.transform(DefaultPluginTransformer.java:146)
    at com.atlassian.plugin.osgi.factory.OsgiPluginFactory.createOsgiPluginJar(OsgiPluginFactory.java:301)
    at com.atlassian.plugin.osgi.factory.OsgiPluginFactory.create(OsgiPluginFactory.java:224)
    at com.atlassian.plugin.loaders.ScanningPluginLoader.deployPluginFromUnit(ScanningPluginLoader.java:155)
    at com.atlassian.plugin.loaders.ScanningPluginLoader.loadAllPlugins(ScanningPluginLoader.java:89)
    at com.atlassian.plugin.loaders.PermissionCheckingPluginLoader.loadAllPlugins(PermissionCheckingPluginLoader.java:24)
    at com.atlassian.plugin.manager.DefaultPluginManager.init(DefaultPluginManager.java:250)
    at com.atlassian.bamboo.container.BambooContainer.init(BambooContainer.java:192)
    at com.atlassian.bamboo.container.BambooContainer.initialise(BambooContainer.java:175)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.initialiseBambooContainer(UpgradeLauncher.java:189)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:94)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.contextInitialized(UpgradeLauncher.java:40)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4887)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5381)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.ClassNotFoundException: com.jcraft.jsch.UserInfo
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 28 more
```

I downloaded `jsch-0.1.52.jar` and put that in my lib/ folder in my Bamboo install dir, which solved this problem, but I'm now getting the following:

```
2015-05-28 14:52:41,603 ERROR [localhost-startStop-1] [BambooHostContainer] Error in plugin class: org.jfrog.bamboo.admin.ServerConfigManager
2015-05-28 14:52:41,603 ERROR [localhost-startStop-1] [PrefixDelegatingModuleFactory] Detected an error (NoClassDefFoundError) instantiating the module for plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin' for module 'artifactoryServerConfigManager': com/atlassian/bandana/BandanaContext.  This error is usually caused by your plugin using a imported component class that itself relies on other packages in the product. You can probably fix this by adding the missing class's package to your <Import-Package> instructions; for more details on how to fix this, see https://developer.atlassian.com/display/DOCS/NoClassDefFoundError .
2015-05-28 14:52:41,604 ERROR [localhost-startStop-1] [BambooPluginUtils] Unable to instantiate module com.atlassian.bamboo.plugin.descriptor.SpringComponentModuleDescriptor
com.atlassian.util.concurrent.LazyReference$InitializationException: java.lang.NoClassDefFoundError: com/atlassian/bandana/BandanaContext
    at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:149)
    at com.atlassian.util.concurrent.LazyReference.get(LazyReference.java:112)
    at com.atlassian.util.concurrent.ResettableLazyReference.get(ResettableLazyReference.java:87)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor$2.call(AbstractBambooModuleDescriptor.java:105)
    at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:87)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.getModule(AbstractBambooModuleDescriptor.java:114)
    at com.atlassian.bamboo.plugin.descriptor.SpringComponentModuleDescriptor.enabled(SpringComponentModuleDescriptor.java:63)
    at com.atlassian.plugin.manager.DefaultPluginManager.notifyModuleEnabled(DefaultPluginManager.java:1694)
    at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModule(DefaultPluginManager.java:1486)
    at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModules(DefaultPluginManager.java:1453)
    at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:908)
    at com.atlassian.bamboo.plugin.BambooPluginManager.addPlugins(BambooPluginManager.java:90)
    at com.atlassian.plugin.manager.DefaultPluginManager.init(DefaultPluginManager.java:291)
    at com.atlassian.bamboo.container.BambooContainer.init(BambooContainer.java:192)
    at com.atlassian.bamboo.container.BambooContainer.initialise(BambooContainer.java:175)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.initialiseBambooContainer(UpgradeLauncher.java:189)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:94)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.contextInitialized(UpgradeLauncher.java:40)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4887)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5381)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/atlassian/bandana/BandanaContext
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
    at java.lang.Class.getConstructors(Class.java:1643)
    at com.atlassian.bamboo.plugin.BambooHostContainer.create(BambooHostContainer.java:32)
    at com.atlassian.plugin.module.ClassPrefixModuleFactory.createModule(ClassPrefixModuleFactory.java:36)
    at com.atlassian.plugin.module.PrefixDelegatingModuleFactory.createModule(PrefixDelegatingModuleFactory.java:100)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.createModule(AbstractBambooModuleDescriptor.java:30)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.access$000(AbstractBambooModuleDescriptor.java:17)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor$1.create(AbstractBambooModuleDescriptor.java:24)
    at com.atlassian.util.concurrent.ResettableLazyReference$InternalReference.create(ResettableLazyReference.java:140)
    at com.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:321)
    at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:143)
    ... 26 more
Caused by: java.lang.ClassNotFoundException: com.atlassian.bandana.BandanaContext
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 38 more
2015-05-28 14:52:41,604 ERROR [localhost-startStop-1] [DefaultPluginManager] There was an error loading the descriptor 'Artifactory Server Configuration Management Component' of plugin 'org.jfrog.bamboo.bamboo-artifactory-plugin'. Disabling.
com.atlassian.util.concurrent.LazyReference$InitializationException: java.lang.NoClassDefFoundError: com/atlassian/bandana/BandanaContext
    at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:149)
    at com.atlassian.util.concurrent.LazyReference.get(LazyReference.java:112)
    at com.atlassian.util.concurrent.ResettableLazyReference.get(ResettableLazyReference.java:87)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor$2.call(AbstractBambooModuleDescriptor.java:105)
    at com.atlassian.bamboo.plugin.BambooPluginUtils.callUnsafeCode(BambooPluginUtils.java:87)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.getModule(AbstractBambooModuleDescriptor.java:114)
    at com.atlassian.bamboo.plugin.descriptor.SpringComponentModuleDescriptor.enabled(SpringComponentModuleDescriptor.java:63)
    at com.atlassian.plugin.manager.DefaultPluginManager.notifyModuleEnabled(DefaultPluginManager.java:1694)
    at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModule(DefaultPluginManager.java:1486)
    at com.atlassian.plugin.manager.DefaultPluginManager.enableConfiguredPluginModules(DefaultPluginManager.java:1453)
    at com.atlassian.plugin.manager.DefaultPluginManager.addPlugins(DefaultPluginManager.java:908)
    at com.atlassian.bamboo.plugin.BambooPluginManager.addPlugins(BambooPluginManager.java:90)
    at com.atlassian.plugin.manager.DefaultPluginManager.init(DefaultPluginManager.java:291)
    at com.atlassian.bamboo.container.BambooContainer.init(BambooContainer.java:192)
    at com.atlassian.bamboo.container.BambooContainer.initialise(BambooContainer.java:175)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.initialiseBambooContainer(UpgradeLauncher.java:189)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.upgradeAndStartBamboo(UpgradeLauncher.java:94)
    at com.atlassian.bamboo.upgrade.UpgradeLauncher.contextInitialized(UpgradeLauncher.java:40)
    at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4887)
    at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5381)
    at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1559)
    at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1549)
    at java.util.concurrent.FutureTask.run(FutureTask.java:266)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
    at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: com/atlassian/bandana/BandanaContext
    at java.lang.Class.getDeclaredConstructors0(Native Method)
    at java.lang.Class.privateGetDeclaredConstructors(Class.java:2663)
    at java.lang.Class.getConstructors(Class.java:1643)
    at com.atlassian.bamboo.plugin.BambooHostContainer.create(BambooHostContainer.java:32)
    at com.atlassian.plugin.module.ClassPrefixModuleFactory.createModule(ClassPrefixModuleFactory.java:36)
    at com.atlassian.plugin.module.PrefixDelegatingModuleFactory.createModule(PrefixDelegatingModuleFactory.java:100)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.createModule(AbstractBambooModuleDescriptor.java:30)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor.access$000(AbstractBambooModuleDescriptor.java:17)
    at com.atlassian.bamboo.plugin.descriptor.AbstractBambooModuleDescriptor$1.create(AbstractBambooModuleDescriptor.java:24)
    at com.atlassian.util.concurrent.ResettableLazyReference$InternalReference.create(ResettableLazyReference.java:140)
    at com.atlassian.util.concurrent.LazyReference$Sync.run(LazyReference.java:321)
    at com.atlassian.util.concurrent.LazyReference.getInterruptibly(LazyReference.java:143)
    ... 26 more
Caused by: java.lang.ClassNotFoundException: com.atlassian.bandana.BandanaContext
    at java.net.URLClassLoader$1.run(URLClassLoader.java:372)
    at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
    at java.security.AccessController.doPrivileged(Native Method)
    at java.net.URLClassLoader.findClass(URLClassLoader.java:360)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
    at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
    ... 38 more
```

Any ideas on this? Of course, this means Bamboo can't load the plugin, as shown:

![](http://i.imgur.com/DeT2SGM.png)

**Comment by gdude2002** [comment]
This issue from 2015 probably doesn't need a stalebot comment, good lord.

Stop using anti-consumer anti-dev tools!
